# movies_data.py
# Database seed data - 100+ well-known movies

MOVIES = [
    # 1950s
    ("Rear Window", 1954, "Thriller", 8.5, "Alfred Hitchcock"),
    ("12 Angry Men", 1957, "Drama", 8.9, "Sidney Lumet"),
    ("The Bridge on the River Kwai", 1957, "Adventure", 8.1, "David Lean"),
    ("Vertigo", 1958, "Thriller", 8.3, "Alfred Hitchcock"),
    ("North by Northwest", 1959, "Thriller", 8.3, "Alfred Hitchcock"),
    ("Some Like It Hot", 1959, "Comedy", 8.2, "Billy Wilder"),
    
    # 1960s
    ("Psycho", 1960, "Horror", 8.5, "Alfred Hitchcock"),
    ("The Apartment", 1960, "Romance", 8.3, "Billy Wilder"),
    ("To Kill a Mockingbird", 1962, "Drama", 8.3, "Robert Mulligan"),
    ("The Good, the Bad and the Ugly", 1966, "Western", 8.8, "Sergio Leone"),
    ("The Graduate", 1967, "Comedy", 8.0, "Mike Nichols"),
    ("2001: A Space Odyssey", 1968, "Sci-Fi", 8.3, "Stanley Kubrick"),
    ("Once Upon a Time in the West", 1968, "Western", 8.5, "Sergio Leone"),
    ("Midnight Cowboy", 1969, "Drama", 7.9, "John Schlesinger"),
    
    # 1970s
    ("The Godfather", 1972, "Crime", 9.2, "Francis Ford Coppola"),
    ("The Godfather Part II", 1974, "Crime", 9.0, "Francis Ford Coppola"),
    ("Chinatown", 1974, "Thriller", 8.2, "Roman Polanski"),
    ("One Flew Over the Cuckoo's Nest", 1975, "Drama", 8.7, "Miloš Forman"),
    ("Jaws", 1975, "Thriller", 8.0, "Steven Spielberg"),
    ("Rocky", 1976, "Drama", 8.1, "John G. Avildsen"),
    ("Taxi Driver", 1976, "Crime", 8.2, "Martin Scorsese"),
    ("Star Wars: Episode IV - A New Hope", 1977, "Sci-Fi", 8.6, "George Lucas"),
    ("Annie Hall", 1977, "Romance", 8.0, "Woody Allen"),
    ("Alien", 1979, "Sci-Fi", 8.5, "Ridley Scott"),
    ("Apocalypse Now", 1979, "Drama", 8.4, "Francis Ford Coppola"),
    
    # 1980s
    ("The Empire Strikes Back", 1980, "Sci-Fi", 8.7, "Irvin Kershner"),
    ("The Shining", 1980, "Horror", 8.4, "Stanley Kubrick"),
    ("Raiders of the Lost Ark", 1981, "Adventure", 8.4, "Steven Spielberg"),
    ("E.T. the Extra-Terrestrial", 1982, "Sci-Fi", 7.9, "Steven Spielberg"),
    ("Blade Runner", 1982, "Sci-Fi", 8.1, "Ridley Scott"),
    ("The Thing", 1982, "Horror", 8.2, "John Carpenter"),
    ("Return of the Jedi", 1983, "Sci-Fi", 8.3, "Richard Marquand"),
    ("Ghostbusters", 1984, "Comedy", 7.8, "Ivan Reitman"),
    ("Back to the Future", 1985, "Sci-Fi", 8.5, "Robert Zemeckis"),
    ("The Breakfast Club", 1985, "Drama", 7.8, "John Hughes"),
    ("The Goonies", 1985, "Adventure", 7.7, "Richard Donner"),
    ("Aliens", 1986, "Sci-Fi", 8.4, "James Cameron"),
    ("Ferris Bueller's Day Off", 1986, "Comedy", 7.8, "John Hughes"),
    ("The Princess Bride", 1987, "Adventure", 8.0, "Rob Reiner"),
    ("Die Hard", 1988, "Action", 8.2, "John McTiernan"),
    ("Who Framed Roger Rabbit", 1988, "Comedy", 7.7, "Robert Zemeckis"),
    ("Indiana Jones and the Last Crusade", 1989, "Adventure", 8.2, "Steven Spielberg"),
    ("Back to the Future Part II", 1989, "Sci-Fi", 7.8, "Robert Zemeckis"),
    
    # 1990s
    ("Goodfellas", 1990, "Crime", 8.7, "Martin Scorsese"),
    ("Terminator 2: Judgment Day", 1991, "Action", 8.5, "James Cameron"),
    ("The Silence of the Lambs", 1991, "Thriller", 8.6, "Jonathan Demme"),
    ("Pulp Fiction", 1994, "Crime", 8.9, "Quentin Tarantino"),
    ("The Shawshank Redemption", 1994, "Drama", 9.3, "Frank Darabont"),
    ("Forrest Gump", 1994, "Romance", 8.8, "Robert Zemeckis"),
    ("The Lion King", 1994, "Animation", 8.5, "Roger Allers"),
    ("Toy Story", 1995, "Animation", 8.3, "John Lasseter"),
    ("Se7en", 1995, "Thriller", 8.6, "David Fincher"),
    ("Fight Club", 1999, "Drama", 8.8, "David Fincher"),
    ("The Matrix", 1999, "Sci-Fi", 8.7, "Lana Wachowski"),
    ("The Sixth Sense", 1999, "Thriller", 8.2, "M. Night Shyamalan"),
    ("American Beauty", 1999, "Drama", 8.3, "Sam Mendes"),
    ("The Green Mile", 1999, "Drama", 8.6, "Frank Darabont"),
    
    # 2000s
    ("Memento", 2000, "Thriller", 8.4, "Christopher Nolan"),
    ("Gladiator", 2000, "Action", 8.5, "Ridley Scott"),
    ("The Lord of the Rings: The Fellowship of the Ring", 2001, "Fantasy", 8.8, "Peter Jackson"),
    ("The Lord of the Rings: The Two Towers", 2002, "Fantasy", 8.8, "Peter Jackson"),
    ("The Lord of the Rings: The Return of the King", 2003, "Fantasy", 8.9, "Peter Jackson"),
    ("Oldboy", 2003, "Thriller", 8.3, "Park Chan-wook"),
    ("Eternal Sunshine of the Spotless Mind", 2004, "Romance", 8.3, "Michel Gondry"),
    ("The Dark Knight", 2008, "Action", 9.0, "Christopher Nolan"),
    ("Wall-E", 2008, "Animation", 8.4, "Andrew Stanton"),
    ("Inglourious Basterds", 2009, "Drama", 8.3, "Quentin Tarantino"),
    ("Up", 2009, "Animation", 8.3, "Pete Docter"),
    ("District 9", 2009, "Sci-Fi", 7.9, "Neill Blomkamp"),
    
    # 2010s
    ("Inception", 2010, "Sci-Fi", 8.8, "Christopher Nolan"),
    ("The Social Network", 2010, "Drama", 7.7, "David Fincher"),
    ("Toy Story 3", 2010, "Animation", 8.3, "Lee Unkrich"),
    ("Black Swan", 2010, "Thriller", 8.0, "Darren Aronofsky"),
    ("The King's Speech", 2010, "Drama", 8.0, "Tom Hooper"),
    ("Drive", 2011, "Action", 7.8, "Nicolas Winding Refn"),
    ("The Avengers", 2012, "Action", 8.0, "Joss Whedon"),
    ("Django Unchained", 2012, "Western", 8.4, "Quentin Tarantino"),
    ("Her", 2013, "Romance", 8.0, "Spike Jonze"),
    ("Frozen", 2013, "Animation", 7.4, "Chris Buck"),
    ("Interstellar", 2014, "Sci-Fi", 8.6, "Christopher Nolan"),
    ("Whiplash", 2014, "Drama", 8.5, "Damien Chazelle"),
    ("Mad Max: Fury Road", 2015, "Action", 8.1, "George Miller"),
    ("The Revenant", 2015, "Adventure", 8.0, "Alejandro González Iñárritu"),
    ("La La Land", 2016, "Romance", 8.0, "Damien Chazelle"),
    ("Moonlight", 2016, "Drama", 7.4, "Barry Jenkins"),
    ("Get Out", 2017, "Horror", 7.8, "Jordan Peele"),
    ("Dunkirk", 2017, "Action", 7.9, "Christopher Nolan"),
    ("Blade Runner 2049", 2017, "Sci-Fi", 8.0, "Denis Villeneuve"),
    ("Spider-Man: Into the Spider-Verse", 2018, "Animation", 8.4, "Peter Ramsey"),
    ("Black Panther", 2018, "Action", 7.3, "Ryan Coogler"),
    ("Parasite", 2019, "Thriller", 8.5, "Bong Joon-ho"),
    ("Joker", 2019, "Crime", 8.4, "Todd Phillips"),
    ("1917", 2019, "Drama", 8.2, "Sam Mendes"),
    
    # 2020s
    ("Tenet", 2020, "Sci-Fi", 7.4, "Christopher Nolan"),
    ("Nomadland", 2020, "Drama", 7.3, "Chloé Zhao"),
    ("Dune", 2021, "Sci-Fi", 8.0, "Denis Villeneuve"),
    ("The Power of the Dog", 2021, "Western", 6.8, "Jane Campion"),
    ("Top Gun: Maverick", 2022, "Action", 8.2, "Joseph Kosinski"),
    ("Everything Everywhere All at Once", 2022, "Sci-Fi", 8.2, "Daniel Kwan"),
    ("The Batman", 2022, "Crime", 7.8, "Matt Reeves"),
    ("Oppenheimer", 2023, "Drama", 8.3, "Christopher Nolan"),
    ("Barbie", 2023, "Comedy", 6.9, "Greta Gerwig"),
    ("Killers of the Flower Moon", 2023, "Crime", 7.7, "Martin Scorsese"),
    ("Poor Things", 2023, "Sci-Fi", 7.6, "Yorgos Lanthimos"),
    ("The Zone of Interest", 2023, "Drama", 7.5, "Jonathan Glazer"),
]